apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hydra-jwks-rotator
  namespace: kyma-system
spec:
  schedule: "36 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "rotate-keys"
        spec:
          restartPolicy: OnFailure
          containers:
            - name: keyr
              image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20200617-32c1f3ff
              command:
                - /bin/bash
                - -c
                - |
                  until curl --head localhost:15000; do echo Waiting for Sidecar; sleep 3; done;
                  echo "Sidecar available";
                  sleep 3;
                  bash <(curl -k https://raw.githubusercontent.com/ory/hydra/master/install.sh) -b . v1.6.0
                  mv ./hydra /usr/local/bin/
                  hydra keys create hydra.openid.id-token -a RS256 --skip-tls-verify --fail-after=2m
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
                  readOnly: true
              env:
                - name: HYDRA_ADMIN_URL
                  value: "http://ory-hydra-admin.kyma-system:4445"
          volumes:
            - name: config-volume
              configMap:
                name: ory-hydra